version: '3.3'
# docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf -v /mosquitto/data -v /mosquitto/log eclipse-mosquitto
services:
  mosquitto:
    image: eclipse-mosquitto
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pidocker01
      restart_policy:
        condition: on-failure
    networks:
      - mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
      - mosquitto_config
    volumes:
      - /data/mosquitto:/data
configs:
  mosquitto_config:
    file: /etc/mosquitto.conf
networks:
  mqtt:
