version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    hostname: mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  mongo-net:
    driver: overlay
    attachable: true
    
volumes:
  mongo-data:
