version: "3.7"
services:
  nuclio-dashboard:
    image: nuclio/dashboard:stable-amd64
    ports:
      - "8070:8070"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp:/tmp"

