version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8801:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

